Architectural documentation
Energinet-DataHub/energy-origin pull request #12
Opened 2022-04-07 13:45 UTC by MartinSchmidt

This is a work in progress, but so you can see the documentation as I work on it.

2022-04-19 08:15 UTC, j4k0bk commented
MessageBus er omdøbt til Event Store. Det er fint nok, men det jeg tiltænkte det til mere end en event store.

Synes der mangler beskrivelse af forskel mellem Message og Command (traditionel terminologi). Hvor en Message er et typisk event, som beskriver noget der skete (fortid), så er en Command noget der ønskes skal ske (fremtid). Commands skal ikke gemmes ift. CQRS, derfor synes jeg MessageBus var et mere passende begreb.

2022-04-19 08:16 UTC, j4k0bk commented
Evt. omdøb system-architecture.md til README.md, så det er GitHub forsiden for doc/architecture mappen.

2022-04-19 08:21 UTC, j4k0bk commented
Dokumentation af Auth flow kan evt. merges ind i dette repo:
https://github.com/Energinet-DataHub/eo-auth/blob/main/doc/authorization_flow.md

2022-04-19 08:35 UTC, j4k0bk commented
Måske en beskrivelse af fremgangsmetoden fra commit til deploy (mellem repos osv)

2022-04-19 08:40 UTC, j4k0bk commented
Beskrivelse, hvordan man får et udviklingsmiljø op og køre lokalt?

2022-04-19 08:55 UTC, MartinSchmidt commented
> MessageBus er omdøbt til Event Store. Det er fint nok, men det jeg tiltænkte det til mere end en event store.
> 
> Synes der mangler beskrivelse af forskel mellem Message og Command (traditionel terminologi). Hvor en Message er et typisk event, som beskriver noget der skete (fortid), så er en Command noget der ønskes skal ske (fremtid). Commands skal ikke gemmes ift. CQRS, derfor synes jeg MessageBus var et mere passende begreb.

I think it could be added as a separate component to cleanly separate commands from events on the conceptual level, even if it is implemented by the same product.

2022-04-19 08:56 UTC, MartinSchmidt commented
> Dokumentation af Auth flow kan evt. merges ind i dette repo:
> https://github.com/Energinet-DataHub/eo-auth/blob/main/doc/authorization_flow.md

Will do once the Auth domain is merged into the monorepo.

2022-04-19 10:15 UTC, CodeReaper commented on doc/architecture/adr/0002-gitops.md
> +one has to consider how one intends to handle ones Continuous Delivery
```suggestion
one has to consider how one intends to handle Continuous Delivery
```

2022-04-19 10:15 UTC, CodeReaper commented on doc/architecture/adr/0002-gitops.md
> +![image](../images/common_gitops_pipeline.png)
This is hard to read in dark mode since there is no background.

2022-04-19 10:15 UTC, CodeReaper commented on doc/architecture/adr/0006-authentication.md
> +**OAuth2 and OIDC** are a well established standard, and will be used.
```suggestion
**OAuth2 and OIDC** are well established standards and will be used.
```

2022-05-18 13:00 UTC, Chrisbh requested changes

2022-05-18 13:00 UTC, Chrisbh commented on doc/api/emissions.md
> +relative is in grams/kwh = total / sum-agg(consumption)
I'd recommend renaming sum-agg to something like sumAgg or sum_agg, whichever you prefer. A hyphen could be misconstrued as a minus.

2022-05-18 13:00 UTC, Chrisbh commented on doc/api/emissions.md
> +      em ->>+ ds: GET /meteringpoint/{gsrn}/measurements  ?from:DateTime  &to: DateTime
```suggestion
    spa->>+ em: GET /api/emissions  ?dateFrom:DateTime  &dateTo: DateTime
    
    em->>+ ds: GET /meteringpoint
    ds--)- em: List<MeteringPointDTO>
    
    loop For each mp
      em ->>+ ds: GET /meteringpoint/{gsrn}/measurements  ?datefrom:DateTime  &dateTo: DateTime 
```
These were the agreed upon names weren't they?

2022-05-18 13:00 UTC, Chrisbh commented on doc/api/emissions.md
> +      em ->>+ ds: GET /measurements  ?from:DateTime  &to: DateTime  &meteringpoint=
```suggestion
    spa->>+ em: GET /api/sources ?dateFrom:DateTime  &dateTo: DateTime
    
    em->>+ ds: GET /meteringpoints
    ds--)- em: List<MeteringPointDTO>
    
    loop For each mp
      em ->>+ ds: GET /measurements  ?dateFrom:DateTime  &dateTo: DateTime  &meteringpoint=
```

2022-05-18 13:00 UTC, Chrisbh commented on doc/architecture/README.md
> +The changes in how energy is handled and consumed is changed in a increasing
```suggestion
The changes in how energy is handled and consumed is changed in an increasing
```

2022-05-18 13:00 UTC, Chrisbh commented on doc/architecture/README.md
> +**no changed** required to other domains.
```suggestion
- **Isolated Domains**: the platform isolates groups of services into domains,
each domain can have a larger responsibility than a single service.
**No changes** required to other domains.
```

2022-05-18 13:00 UTC, Chrisbh commented on doc/architecture/README.md
> +This will enabled a shared benefit over time.
```suggestion
This will enable a shared benefit over time.
```

2022-05-18 13:00 UTC, Chrisbh commented on doc/architecture/adr/0002-gitops.md
> +In GitOps a **Operator** is used to keep the environment in sync with the repository.
```suggestion
In GitOps an **Operator** is used to keep the environment in sync with the repository.
```

2022-05-18 14:22 UTC, CodeReaper commented
@MartinSchmidt We have neglected to consider the routing of the API endpoints, all endpoints that resides on the auth domain has a prefix of `/api/auth/**`. The other endpoints will need similar prefixes to the domains they reside on.

2022-05-19 07:40 UTC, CodeReaper commented on doc/architecture/adr/0003-event-store.md
> +on how to store and migrate data.
```suggestion
Storing the events in a centrally shared store removes the criticality in each domain
on how to store and migrate data.
```

2022-05-19 07:40 UTC, CodeReaper commented on doc/architecture/adr/0003-event-store.md
> +Each domain can build and optimized datastore or precalculate results needed.
```suggestion
Each domain can build an optimized datastore or precalculate results needed.
```

2022-05-19 08:54 UTC, CodeReaper commented on doc/api/datasync.md
> +## Create relations for company
```suggestion
## Internal call structure
```

2022-05-19 08:54 UTC, CodeReaper commented on doc/api/datasync.md
> +    auth-->>-spa: jwt / opaque token (cookie)
```suggestion
    spa->>+auth: login
        auth ->>+ datasync: POST: /relations  {tin=12345678}
        datasync -->>- auth: Success
    auth-->>-spa: jwt / opaque token (cookie)
```

2022-05-19 08:54 UTC, CodeReaper commented on doc/api/emissions.md
> +sum-agg is Sum for each "bucket" in the aggregation level selected.
```suggestion
```

### Calculation

sum-agg is Sum for each "bucket" in the aggregation level selected.
```

2022-05-19 08:54 UTC, CodeReaper commented on doc/api/emissions.md
> +    em->>- spa: TotalEmissionDTO
```suggestion
sequenceDiagram
    participant spa as Single Page Application
    participant em as Emissions Domain
    participant ds as DataSync Domain
    participant eds as EnergiDataService

    spa->>+ em: GET /api/emissions  ?dateFrom:DateTime  &dateTo: DateTime
    
    em->>+ ds: GET /meteringpoints
    ds--)- em: List<MeteringPointDTO>
    
    loop For each mp
      em ->>+ ds: GET /meteringpoints/{gsrn}/measurements  ?datefrom:DateTime  &dateTo: DateTime 
        
      ds --)- em: List< MeasurementDTO>
    end
    em->>+ eds: GET https://www.energidataservice.dk/tso-electricity/declarationemissionhour
    eds--)- em: {...}

    em->> em: calculateEmissions

    em->>- spa: TotalEmissionDTO
```

2022-05-19 08:54 UTC, CodeReaper commented on doc/architecture/README.md
> +green transition.
```suggestion
The changes in how energy is handled and consumed is changing in an increasing
manner, so a platform that can handle these challenges is needed to enable the
green transition.
```

2022-05-19 08:54 UTC, CodeReaper commented on doc/architecture/README.md
> +The goal of the architecture is to:
```suggestion
The goals of the architecture are:
```

2022-05-19 08:54 UTC, CodeReaper commented on doc/architecture/README.md
> +integrates with each other.
```suggestion
This view explores how the different components that the platform is built from
integrates with each other.
```

2022-05-19 08:54 UTC, CodeReaper commented on doc/architecture/README.md
> +- [Measurement](domains/measurements.md)
This and the linked document seems irrelevant with the addition of the `docs/api` area, can this (and the linked document) be deleted?

2022-05-19 08:54 UTC, CodeReaper commented on doc/architecture/adr/0002-gitops.md
> +* Configuration of the environment up until the operator is running is required to be push-based.
```suggestion
* Configuration of the environment before the operator is running is required to be push-based.
```

2022-05-19 08:54 UTC, CodeReaper commented on doc/architecture/adr/0003-event-store.md
> +the usecase from the event store.
```suggestion
When a new domain is created it can build its state in a query model optimized to
its usecase from the event store.
```

2022-05-19 09:10 UTC, CodeReaper commented
We have previously discussed `meteringPointId` vs. `GSRN`, this is also something that we should align.

2022-05-19 11:54 UTC, RasmusGodske commented on doc/api/best-practices.md
> +### Aggregation
This sections seems out of place within best practices. It does not seem like a practice to me but rather a shared property.

2022-05-19 11:54 UTC, RasmusGodske commented on doc/api/datasync.md
> +- meteringpoint: 17 digit integer id of a meteringpoint, multiple can be seperated with ;
```suggestion
- meteringpoint: 18 digit integer id(GSRN) of a meteringpoint, multiple can be seperated with ;
```

2022-05-20 12:55 UTC, CodeReaper approved these changes

2022-05-23 06:56 UTC, Chrisbh approved these changes

2022-05-23 07:34 UTC, merged