Database event store
Energinet-DataHub/energy-origin pull request #130
Opened 2022-08-31 08:41 UTC by CodeReaper

2022-09-02 09:15 UTC, MartinSchmidt requested changes

2022-09-02 09:15 UTC, MartinSchmidt commented on libraries/dotnet/EnergyOriginEventStore/EnergyOriginEventStore/EventStore/Database/DatabaseEventStore.cs
> +    #region IEventStore
fluff

2022-09-02 09:15 UTC, MartinSchmidt commented on libraries/dotnet/EnergyOriginEventStore/EnergyOriginEventStore/EventStore/Database/DatabaseEventConsumerBuilder.cs
> +    private string? pointer;
```suggestion
    private string pointer = "0";
```

2022-09-02 09:15 UTC, MartinSchmidt commented on libraries/dotnet/EnergyOriginEventStore/EnergyOriginEventStore/EventStore/Database/DatabaseEventConsumer.cs
> +        await semaphore.WaitAsync();
remove semaphore!
move do while loop into Work() -> rename to worker

2022-09-02 09:15 UTC, MartinSchmidt commented on libraries/dotnet/EnergyOriginEventStore/EnergyOriginEventStore/EventStore/Database/DatabaseEventConsumer.cs
> +        });
```suggestion
        Task.Run(async worker());
```

2022-09-02 09:15 UTC, MartinSchmidt commented on libraries/dotnet/EnergyOriginEventStore/EnergyOriginEventStore.Tests/SqliteDatabaseEventContext.cs
> +    };
cleanup

2022-09-02 09:15 UTC, MartinSchmidt commented on libraries/dotnet/EnergyOriginEventStore/EnergyOriginEventStore.Tests/EventStoreTests.cs
> +    private static IEnumerable<object[]> Data() => new List<object[]>
Find better name

2022-09-02 09:15 UTC, MartinSchmidt commented on libraries/dotnet/EnergyOriginEventStore/EnergyOriginEventStore.Tests/EventStoreTests.cs
> +    [MemberData(nameof(Data))]
try with inlinedata...

2022-09-07 09:02 UTC, CodeReaper commented
Notice I removing FlatFile as a viable option for event store. Only memory event store and database event store is considered stable.

2022-09-07 09:19 UTC, Exobitt submitted a review, later dismissed

2022-09-07 14:03 UTC, MartinSchmidt submitted a review, later dismissed

2022-09-08 07:38 UTC, Exobitt approved these changes

2022-09-08 07:39 UTC, merged