Add terms endpoint
Energinet-DataHub/energy-origin pull request #132
Opened 2022-09-02 11:58 UTC by ckr123

2022-09-05 10:02 UTC, CodeReaper requested changes

2022-09-05 10:02 UTC, CodeReaper commented on domains/auth/Auth.API/UnitTests/Controllers/TestTermsController.cs
> +    }
Long names again :) 


```suggestion
    private readonly Mock<IPrivacyPolicyStorage> storage = new();

    private readonly TermsController termsController;

    public TestTermsController() => termsController = new(storage.Object);

    [Fact]
    public async Task Get_Terms_ReturnsPrivacyPolicy()
    {
        var fakePolicy = new PrivacyPolicy(
            "<html>nice privacy</html>",
            "v1",
            "PrivacyPolicy"
        );
        storage
            .Setup(p => p.Get())
            .ReturnsAsync(() => fakePolicy);

        var response = await termsController.Get();
        var result = response.Result as OkObjectResult;
        var policy = result?.Value as PrivacyPolicy;

        Assert.Equal(fakePolicy.Version, policy?.Version);
        Assert.Equal(fakePolicy.Terms, policy?.Terms);
        Assert.Equal(fakePolicy.Headline, policy?.Headline);
    }
```

2022-09-05 10:02 UTC, CodeReaper commented on domains/auth/Auth.API/UnitTests/Repository/TestPrivacyPolicyStorage.cs
> +public class TestPrivacyPolicyStorage
Same deal as before with long names and folder traversing.

2022-09-06 06:43 UTC, ckr123 commented on domains/auth/Auth.API/API/Repository/PrivacyPolicyStorage.cs
> +            .OrderByDescending(f => f.LastWriteTime)
This is from the python code. Is it not the same kubernetes process?

2022-09-06 06:44 UTC, ckr123 commented on domains/auth/Auth.API/IntegrationTests/Controllers/TestTermsController.cs
> +        .FullName + "\\resources";
Had a talk with @duizer it doesnt seem like it. Correct me if i am wrong Paul

2022-09-06 06:45 UTC, ckr123 commented on domains/auth/Auth.API/API/Program.cs
> +[assembly: InternalsVisibleTo("IntegrationTests")]
Where is that updated?

2022-09-06 10:25 UTC, ckr123 commented on domains/auth/Auth.API/API/Program.cs
> +});
As agreed with @duizer we will name the ENV variable so it is able to be parsed using iptions

2022-09-06 10:25 UTC, ckr123 commented on domains/auth/Auth.API/IntegrationTests/Controllers/TestTermsController.cs
> +        .FullName + "\\resources";
There is no pretty way of doing thos.

2022-09-06 10:26 UTC, ckr123 commented on domains/auth/Auth.API/IntegrationTests/Controllers/TestTermsController.cs
> +        Assert.True(response.IsSuccessStatusCode);
This test will be removed and be covered in the apptest as agreed with @duizer

2022-09-06 17:56 UTC, CodeReaper approved these changes

2022-09-07 06:06 UTC, merged