adr authorization
Energinet-DataHub/energy-origin pull request #1412
Opened 2024-08-28 10:30 UTC by TopSwagCode

2024-08-28 11:15 UTC, sahma19 requested changes

2024-08-28 11:15 UTC, sahma19 commented on doc/architecture/adr/0027-Authentication-and-Authorization.md
> +* Deciders: @tnickelsen, @ckr123, @sahma19, @TopSwagCode, @martinhenningjensen
Deciders were @sahma19 @TopSwagCode @martinhenningjensen @rvplauborg @Sondergaard

2024-08-28 11:15 UTC, sahma19 commented on doc/architecture/adr/0027-Authentication-and-Authorization.md
> +* Date: 2025-01-01
Date was 2024-07-02

2024-08-28 11:15 UTC, sahma19 commented on doc/architecture/adr/0027-Authentication-and-Authorization.md
> +We have choosen to go with Azure B2C, because it's a vetted secure hosted solution, that is already used within the company and most likely going to be the standard in the future. We had acritect in
Does all this correspond with what is written here? Should it?

https://energinet.atlassian.net/wiki/spaces/EnergyOrigin/pages/640974851/OAuth2+PoC

2024-08-28 11:47 UTC, ckr123 commented on doc/architecture/adr/0028-Wallet-Proxy.md
> +# Metric naming convention
Wallet Proxy*

2024-08-28 11:48 UTC, ckr123 commented on doc/architecture/adr/0028-Wallet-Proxy.md
> +* Date: 2025-01-01
Wrong date

2024-08-29 05:36 UTC, TopSwagCode commented on doc/architecture/adr/0027-Authentication-and-Authorization.md
> +We have choosen to go with Azure B2C, because it's a vetted secure hosted solution, that is already used within the company and most likely going to be the standard in the future. We had acritect in
You tell me? :D I wrote from my memory.

2024-08-29 07:23 UTC, martinhenningjensen approved these changes

2024-09-02 05:30 UTC, martinhenningjensen submitted a review, later dismissed

2024-09-02 05:30 UTC, martinhenningjensen commented on doc/architecture/adr/0027-Authentication-and-Authorization.md
> +* A mitid needs to be able to give 3rd party system access to work on their data.
mitid _user_ needs

2024-09-02 05:30 UTC, martinhenningjensen commented on doc/architecture/adr/0027-Authentication-and-Authorization.md
> +* A user needs to be able to give 3rd party mitid user access to work on their data.
A _mitid_ user needs

2024-09-02 05:30 UTC, martinhenningjensen commented on doc/architecture/adr/0027-Authentication-and-Authorization.md
> +We have choosen to go with Azure B2C, because it's a vetted secure hosted solution, that is already used within the company and most likely going to be the standard in the future. We had architect in
_We included architects in the decision_

2024-09-02 05:30 UTC, martinhenningjensen commented on doc/architecture/adr/0028-Wallet-Proxy.md
> +Make auhtorization proxy for wallet:
typo: _authorization_

2024-09-02 05:30 UTC, martinhenningjensen commented on doc/architecture/adr/0028-Wallet-Proxy.md
> +Make a new subsystem to protect wallet behind as a proxy having custmo logic.
typo: _custom_

2024-09-02 05:47 UTC, sahma19 submitted a review, later dismissed

2024-09-02 05:47 UTC, sahma19 commented on doc/architecture/adr/0027-Authentication-and-Authorization.md
> +* A mitid needs to be able to give 3rd party system access to work on their data.
Ditto

2024-09-02 05:47 UTC, sahma19 commented on doc/architecture/adr/0027-Authentication-and-Authorization.md
> +* A user needs to be able to give 3rd party mitid user access to work on their data.
Ditto

2024-09-04 05:31 UTC, TopSwagCode commented on doc/architecture/adr/0028-Wallet-Proxy.md
> +Make auhtorization proxy for wallet:
?

2024-09-04 06:06 UTC, martinhenningjensen approved these changes

2024-09-04 08:22 UTC, merged