Vcluster/transfer poa
Energinet-DataHub/energy-origin pull request #1628
Opened 2024-12-03 20:04 UTC by TopSwagCode

2024-12-11 05:39 UTC, TopSwagCode commented on domains/transfer/Transfer.API/API.IntegrationTests/MockAuthorizationClient.cs
> +        await Task.Delay(1);
remove Task delay.

2024-12-11 05:40 UTC, TopSwagCode commented on domains/transfer/Transfer.API/API.IntegrationTests/Transfer/Api/Controllers/TransferAgreementProposalsControllerTests.cs
> +        result.StatusCode.Should().Be(HttpStatusCode.Created);
Should we stay consistent only checking status codes like the other tests?

2024-12-11 05:41 UTC, TopSwagCode commented on domains/transfer/Transfer.API/API.IntegrationTests/Transfer/Api/Controllers/TransferAgreementsControllerTest.cs
> +        var senderOrganizationId = new Guid("7adc659d-ad17-4d2d-a92f-b9904bbd306d");
Change to be random Guids and chance Mock to setup / cleanup between tests.

2024-12-11 05:41 UTC, TopSwagCode commented on domains/transfer/Transfer.API/API.IntegrationTests/Transfer/Api/Controllers/TransferAgreementsControllerTest.cs
> +    // public async Task CreatePOATransferAgreementWithSelf_ShouldCreateTransferAgreement_WhenInputIsValid()
Can be added after MockAuth is changed to seed for each test instead of shared.

2024-12-11 05:42 UTC, TopSwagCode commented on domains/transfer/Transfer.API/API.IntegrationTests/Transfer/Api/Controllers/TransferAgreementsControllerTest.cs
> +    [Fact] // TODO: Finish this test.
Todo :D

2024-12-11 05:43 UTC, TopSwagCode commented on domains/transfer/Transfer.API/API/Program.cs
> +    client.BaseAddress = new Uri(builder.Configuration["Authorization:BaseUrl"]!); // Do we want to fail in other way than nullpointer?
TODO: Update EO Base with this new configuration.

2024-12-11 05:44 UTC, TopSwagCode commented on domains/transfer/Transfer.API/API/Program.cs
> +.AddPolicyHandler(RetryPolicy())
Adding Retry and Circuit breaker policy. This could be a start of something new? https://www.youtube.com/watch?v=zBG-sEGlULs

2024-12-11 05:45 UTC, TopSwagCode commented on domains/transfer/Transfer.API/API/Transfer/Api/Clients/AuthorizationClient.cs
> +    {
delete. Not used.

2024-12-11 05:46 UTC, TopSwagCode commented on domains/transfer/Transfer.API/API/Transfer/Api/Clients/AuthorizationClient.cs
> +public class WebContextBearerTokenService(IHttpContextAccessor HttpContextAccessor) : IBearerTokenService
Ensure these are added in Program.cs

2024-12-11 05:47 UTC, TopSwagCode commented on domains/transfer/Transfer.API/API/Transfer/Api/[Features]/CreateTransferAgreementProposalCommand.cs
> +public static class UserOrganizationConsentsResponseExtensions
move to own file.

2024-12-11 19:42 UTC, TopSwagCode commented
![image](https://github.com/user-attachments/assets/a0cc0592-2144-43dc-a922-cfcf5e62d535)
Screenshot of POA transfer proposals created.
But there is a bug in frontend.

2024-12-12 09:04 UTC, martinhenningjensen requested changes

2024-12-12 09:04 UTC, martinhenningjensen commented on domains/transfer/Transfer.API/API/Transfer/Api/[Features]/CreateTransferAgreementCommand.cs
> +        if (consents == null)
What did { and } ever do to you?

2024-12-12 09:04 UTC, martinhenningjensen commented on domains/transfer/Transfer.API/API/Transfer/Api/[Features]/CreateTransferAgreementCommand.cs
> +        var consents = await AuthorizationClient.GetConsentsAsync();
Sådan helt principielt, vil vi gerne have afhængighed til eksterne systemer i command handler?

2024-12-12 09:22 UTC, TopSwagCode commented on domains/transfer/Transfer.API/API.IntegrationTests/Transfer/Api/Controllers/TransferAgreementProposalsControllerTests.cs
> +        var authenticatedClient = factory.CreateB2CAuthenticatedClient(sub, orgId.Value, orgIds: $"{senderOrganizationId} {receiverOrganizationId}");
fixed

2024-12-12 10:32 UTC, martinhenningjensen approved these changes

2024-12-12 10:33 UTC, martinhenningjensen approved these changes

2024-12-12 10:51 UTC, merged