New ADR - message-broker
Energinet-DataHub/energy-origin pull request #213
Opened 2023-01-19 10:17 UTC by anna-knudsen

2023-01-20 10:46 UTC, Exobitt approved these changes

2023-01-23 08:19 UTC, duizer requested changes

2023-01-23 08:19 UTC, duizer commented on doc/architecture/adr/0019-message-broker.md
> +Lots of documentation
```suggestion
* Easy setup
* Lots of documentation
```

2023-01-23 08:19 UTC, duizer commented on doc/architecture/adr/0019-message-broker.md
> +RabbitMQ seems to be a simple message broker and not much else, which is exactly what we need.
This is a minor thing: The other paragraphs starts with the name of the technology and then a colon. This section does not.

2023-01-23 08:19 UTC, duizer commented on doc/architecture/adr/0019-message-broker.md
> +Kafka:
The rendered page will not have a break line. So maybe:

* Make this bold
* Use a header (###)
* Delete the line

2023-01-23 08:19 UTC, duizer commented on doc/architecture/adr/0019-message-broker.md
> +* Status:
Please set Status to "Proposed". Also add "PROPOSAL" to the file name as described here: https://github.com/Energinet-DataHub/energy-origin/blob/main/doc/architecture/adr/process.md. The process description is unfortunately not 100% updated, so please also update the README file with a link to this ADR.

2023-01-23 08:19 UTC, duizer commented on doc/architecture/adr/0019-message-broker.md
> +We also want a message broker that is fairly easy to set up.
I suggest that the Context states that this is for the Certificates domain specifically. ADR's are for the entire system, but in this case it is based on the needs within the Certificates domain.

2023-01-23 08:19 UTC, duizer commented on doc/architecture/adr/0019-message-broker.md
> +We are not yet 100% sure that RabbitMQ can handle the number of messages we need, and we are aware that RabbitMQ can not be scaled to the extent that Kafka can.
Is it possible to add the number of messages that we currently think that we need?

2023-01-27 12:31 UTC, duizer approved these changes

2023-01-27 12:45 UTC, Exobitt approved these changes
lgtm

2023-01-27 12:45 UTC, merged