Update validation of dotnet projects
Energinet-DataHub/energy-origin pull request #784
Opened 2024-03-08 10:56 UTC by CodeReaper

- Do not run tests for already tested and approved changes.
- Output logs for failing tests and a single passed line for passing tests.

2024-03-08 13:29 UTC, ole-kaas approved these changes

2024-03-08 15:12 UTC, sahma19 requested changes
So how exactly would this work?

Say I open up a pull request, there is new business logic, and 10 unit tests for it.

The pipeline will run the validation step, and it will pass if all 10 unit tests pass.

Let's say I afterwards make a new commit to the pull request. A commit that slightly alters the business logic.

Would the pipeline still run the 10 unit tests again?

2024-03-08 15:56 UTC, CodeReaper commented
> So how exactly would this work?
> 
> Say I open up a pull request, there is new business logic, and 10 unit tests for it.
> 
> The pipeline will run the validation step, and it will pass if all 10 unit tests pass.
> 
> Let's say I afterwards make a new commit to the pull request. A commit that slightly alters the business logic.
> 
> Would the pipeline still run the 10 unit tests again?

Yes - This only changes what happens after a PR is merged.

2024-03-09 13:36 UTC, sahma19 approved these changes

2024-03-11 09:41 UTC, merged